version: '3'
services:
  emitter:
    build:
      context: ./emitter
    depends_on:
      - listener

  listener:
    build:
      context: ./listener
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:8080'

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
